### ISSUE TITLE
Remove log message

### ISSUE THREAD

**Issue by rsmbyk** [zhiyzuo/python-modularity-maximization#5]
How do I remove the log message when calling `modularity_maximization.utils.get_modularity` functions?

It keeps printing `Calculating modularity for undirected graph` every time I call this function.

**Comment by zhiyzuo** [comment]
this is because I put a print in the code [here](https://github.com/zhiyzuo/python-modularity-maximization/blob/488c02631a261dc366e385412084457534d7d8e0/modularity_maximization/utils.py#L88).

if you're using it in jupyter notebook, you could use the `%%capture` to get rid of all the output in the cell.

**Comment by rsmbyk** [comment]
Maybe you can add an option/argument to turn on/off printing of the log message.
